name: binder-environment
channels:
  - conda-forge
dependencies:
  - python>=3.5
  - numpy
  - vtk
  - pyqt
  - itkwidgets>=0.25.2
  - tqdm
  - pip
  - pip:
    - pandas
    - matplotlib
    - scipy
    - requests
    - psutil
    - pyvista
