name: binder-environment
channels:
  - conda-forge
dependencies:
  - python==3.7
  - numpy
  - pip
  - pip:
    - pandas
    - matplotlib
    - scipy
    - requests
    - psutil
    - pyvista
    - vtk==8.1.2
